/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.una.proyecto3_progra3.view.bloque;

import com.una.proyecto3_progra3.controller.categoria.BloqueInterface;
import com.una.proyecto3_progra3.controller.categoria.CategoriaController;
import com.una.proyecto3_progra3.view.FrmMain;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Dylan M
 */
public class frmAgregarBloque extends javax.swing.JFrame {

    BloqueInterface bloque;
    
        
    public frmAgregarBloque() {
        bloque = new CategoriaController();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtCodigoBloque = new javax.swing.JTextField();
        txtNombreBloque = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        AMD = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        labelCodigo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(976, 578));
        setResizable(false);

        panelPrincipal.setBackground(java.awt.Color.white);
        panelPrincipal.setForeground(java.awt.Color.black);
        panelPrincipal.setPreferredSize(new java.awt.Dimension(976, 578));
        panelPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPrincipalMouseEntered(evt);
            }
        });

        labelTitle.setBackground(java.awt.Color.black);
        labelTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelTitle.setText("INGRESO DE BLOQUE AL SISTEMA");

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(242, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setToolTipText("");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnVolver.setBackground(new java.awt.Color(0, 0, 0));
        btnVolver.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        btnVolver.setForeground(java.awt.Color.white);
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtCodigoBloque.setForeground(java.awt.Color.lightGray);
        txtCodigoBloque.setText("Digite el codigo del bloque");
        txtCodigoBloque.setToolTipText("");
        txtCodigoBloque.setBorder(null);
        txtCodigoBloque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoBloqueMouseClicked(evt);
            }
        });
        txtCodigoBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoBloqueActionPerformed(evt);
            }
        });
        txtCodigoBloque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoBloqueKeyTyped(evt);
            }
        });

        txtNombreBloque.setForeground(java.awt.Color.lightGray);
        txtNombreBloque.setText("Digite el nombre del bloque");
        txtNombreBloque.setToolTipText("");
        txtNombreBloque.setBorder(null);
        txtNombreBloque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreBloqueMouseClicked(evt);
            }
        });
        txtNombreBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBloqueActionPerformed(evt);
            }
        });
        txtNombreBloque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreBloqueKeyTyped(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AMD.setFont(new java.awt.Font("Maven Pro Medium", 1, 36)); // NOI18N
        AMD.setForeground(java.awt.Color.white);
        AMD.setText("AMD");
        AMD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(AMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        jPanel3.setBackground(java.awt.Color.black);
        jPanel3.setForeground(java.awt.Color.white);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText(" ©2022 Reservados todos los derechos de autor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel2)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        labelEstado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(0, 0, 0));
        labelEstado.setText("Estado del Bloque: ");

        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        ComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEstadoActionPerformed(evt);
            }
        });

        labelCodigo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigo.setText("Codigo:");

        labelNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("Nombre:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelTitle)
                        .addGroup(panelPrincipalLayout.createSequentialGroup()
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelCodigo)
                                .addComponent(labelNombre))
                            .addGap(100, 100, 100)
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoBloque, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jSeparator1))))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelEstado)
                        .addGap(56, 56, 56)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(ComboBoxEstado, 0, 166, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(txtNombreBloque, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addGap(354, 354, 354))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(labelTitle)
                .addGap(41, 41, 41)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(txtNombreBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))))
        );

        txtCodigoBloque.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPrincipalMouseEntered

        if(this.txtNombreBloque.getText().isBlank()){
            this.txtNombreBloque.setText("Digite el nombre del bloque");
            this.txtNombreBloque.setForeground(Color.LIGHT_GRAY);
        }
        if(this.txtCodigoBloque.getText().isBlank()){
            this.txtCodigoBloque.setText("Digite el codigo del bloque");
            this.txtCodigoBloque.setForeground(Color.LIGHT_GRAY);
        }
    
        
        
    }//GEN-LAST:event_panelPrincipalMouseEntered

    private void txtNombreBloqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreBloqueKeyTyped
        if(this.txtNombreBloque.getText().equals("Digite el nombre del bloque")){
            this.txtNombreBloque.setText("");
            this.txtNombreBloque.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreBloqueKeyTyped

    private void txtNombreBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBloqueActionPerformed

    private void txtNombreBloqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreBloqueMouseClicked
        if(this.txtNombreBloque.getText().equals("Digite el nombre del bloque")){
            this.txtNombreBloque.setText("");
            this.txtNombreBloque.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreBloqueMouseClicked

    private void txtCodigoBloqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoBloqueKeyTyped
        if(this.txtCodigoBloque.getText().equals("Digite el codigo del bloque")){
            this.txtCodigoBloque.setText("");
            this.txtCodigoBloque.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCodigoBloqueKeyTyped

    private void txtCodigoBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoBloqueActionPerformed

    private void txtCodigoBloqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoBloqueMouseClicked
        if(this.txtCodigoBloque.getText().equals("Digite el codigo del bloque")){
            this.txtCodigoBloque.setText("");
            this.txtCodigoBloque.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtCodigoBloqueMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        this.btnVolver.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        this.btnVolver.setBackground(Color.darkGray);
        this.btnVolver.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        FrmMain main = new FrmMain();
        main.setVisible(true);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        this.btnAceptar.setBackground(Color.BLACK);
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        this.btnAceptar.setBackground(Color.darkGray);
        this.btnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        String data[] = {this.txtCodigoBloque.getText(),this.txtNombreBloque.getText(),this.ComboBoxEstado.getSelectedItem().toString()};
        boolean bandera = true;
        if(this.txtCodigoBloque.getText().isBlank() || this.txtCodigoBloque.getText().equals("Digite el codigo del bloque") ){
            bandera = false;
        }
        if( this.txtNombreBloque.getText().isBlank() ||  this.txtNombreBloque.getText().equals("Digite el nombre del bloque") ){
            bandera = false;
        }
        
        if(bandera == true){
            if(bloque.insertBloque(data) ){
                JOptionPane.showMessageDialog(rootPane, "Se inserto correctamente");
            
             }else{
                JOptionPane.showMessageDialog(this, "Error al ingresar bloque", "ERROR", JOptionPane.ERROR_MESSAGE);
        
            }
        }else{
             JOptionPane.showMessageDialog(this, "Error! espacios en blanco", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
         cleanFrmAgregar();
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void ComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEstadoActionPerformed
    private void cleanFrmAgregar(){
        this.txtCodigoBloque.setText("Digite el codigo del bloque");
        this.txtCodigoBloque.setForeground(Color.LIGHT_GRAY);
        
        this.txtNombreBloque.setText("Digite el nombre del bloque");
        this.txtNombreBloque.setForeground(Color.LIGHT_GRAY);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMD;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtCodigoBloque;
    private javax.swing.JTextField txtNombreBloque;
    // End of variables declaration//GEN-END:variables
}
