/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.una.proyecto3_progra3.view;

import com.una.proyecto3_progra3.view.usuario.frmAgregarU;
import com.una.proyecto3_progra3.view.usuario.frmEliminarU;
import com.una.proyecto3_progra3.view.usuario.frmModificarU;
import java.awt.Color;
import java.awt.Cursor;


/**
 *
 * @author Dylan M
 */
public class FrmMain extends javax.swing.JFrame {

    frmAgregarU l;
    frmModificarU l2;
    frmEliminarU l3;
    public FrmMain() {
        l2 = new frmModificarU();
        l = new frmAgregarU();
        l3 = new frmEliminarU();
        initComponents();
        this.panelUserOptions.setVisible(false);
        this.panelDeptOptions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainerModules = new javax.swing.JPanel();
        menuUser = new javax.swing.JLabel();
        AMD = new javax.swing.JLabel();
        departamentoMenu = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        menuCategory = new javax.swing.JLabel();
        menuProductos = new javax.swing.JLabel();
        menuProductos1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelUserOptions = new javax.swing.JPanel();
        panelUserD = new javax.swing.JPanel();
        labelDelete = new javax.swing.JLabel();
        panelUserR = new javax.swing.JPanel();
        labelRegistrar = new javax.swing.JLabel();
        panelUserM = new javax.swing.JPanel();
        labelModify = new javax.swing.JLabel();
        panelUserL = new javax.swing.JPanel();
        labelMostrar = new javax.swing.JLabel();
        panelDeptOptions = new javax.swing.JPanel();
        panelDeptD = new javax.swing.JPanel();
        labelDeleteDept = new javax.swing.JLabel();
        panelDeptA = new javax.swing.JPanel();
        labelAgregarDept = new javax.swing.JLabel();
        panelDeptM = new javax.swing.JPanel();
        labelModifyDept = new javax.swing.JLabel();
        panelDeptL = new javax.swing.JPanel();
        labelMostrarDepts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContainerModules.setBackground(new java.awt.Color(0, 0, 0));
        panelContainerModules.setForeground(java.awt.Color.white);
        panelContainerModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelContainerModulesMouseEntered(evt);
            }
        });
        panelContainerModules.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuUser.setBackground(java.awt.Color.black);
        menuUser.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        menuUser.setForeground(java.awt.Color.white);
        menuUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuUser.setText("Usuarios");
        menuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuUserMouseExited(evt);
            }
        });
        panelContainerModules.add(menuUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 110, -1));

        AMD.setFont(new java.awt.Font("Maven Pro Medium", 1, 36)); // NOI18N
        AMD.setForeground(java.awt.Color.white);
        AMD.setText("AMD");
        AMD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelContainerModules.add(AMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        departamentoMenu.setBackground(java.awt.Color.black);
        departamentoMenu.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        departamentoMenu.setForeground(java.awt.Color.white);
        departamentoMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departamentoMenu.setText("Departamentos");
        departamentoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departamentoMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departamentoMenuMouseExited(evt);
            }
        });
        panelContainerModules.add(departamentoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 170, 30));

        exitButton.setBackground(java.awt.Color.black);
        exitButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        exitButton.setForeground(java.awt.Color.white);
        exitButton.setText("X");
        exitButton.setBorder(null);
        exitButton.setFocusable(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        panelContainerModules.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 20, 20));

        menuCategory.setBackground(java.awt.Color.black);
        menuCategory.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        menuCategory.setForeground(java.awt.Color.white);
        menuCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCategory.setText("Categorias");
        menuCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuCategoryMouseExited(evt);
            }
        });
        panelContainerModules.add(menuCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 110, -1));

        menuProductos.setBackground(java.awt.Color.black);
        menuProductos.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        menuProductos.setForeground(java.awt.Color.white);
        menuProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProductos.setText("Productos");
        menuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuProductosMouseExited(evt);
            }
        });
        panelContainerModules.add(menuProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 110, -1));

        menuProductos1.setBackground(java.awt.Color.black);
        menuProductos1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        menuProductos1.setForeground(java.awt.Color.white);
        menuProductos1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProductos1.setText("Reportes");
        menuProductos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuProductos1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuProductos1MouseExited(evt);
            }
        });
        panelContainerModules.add(menuProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 110, -1));

        getContentPane().add(panelContainerModules, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUserOptions.setBackground(java.awt.Color.black);
        panelUserOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelUserOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUserOptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUserOptionsMouseExited(evt);
            }
        });

        panelUserD.setBackground(java.awt.Color.black);

        labelDelete.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelDelete.setForeground(java.awt.Color.white);
        labelDelete.setText("ELIMINAR");
        labelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDeleteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUserDLayout = new javax.swing.GroupLayout(panelUserD);
        panelUserD.setLayout(panelUserDLayout);
        panelUserDLayout.setHorizontalGroup(
            panelUserDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserDLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserDLayout.setVerticalGroup(
            panelUserDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserDLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelDelete)
                .addContainerGap())
        );

        panelUserR.setBackground(java.awt.Color.black);

        labelRegistrar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelRegistrar.setForeground(java.awt.Color.white);
        labelRegistrar.setText("REGISTRAR");
        labelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUserRLayout = new javax.swing.GroupLayout(panelUserR);
        panelUserR.setLayout(panelUserRLayout);
        panelUserRLayout.setHorizontalGroup(
            panelUserRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserRLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserRLayout.setVerticalGroup(
            panelUserRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUserM.setBackground(java.awt.Color.black);

        labelModify.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelModify.setForeground(java.awt.Color.white);
        labelModify.setText("MODIFICAR");
        labelModify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModifyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModifyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModifyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUserMLayout = new javax.swing.GroupLayout(panelUserM);
        panelUserM.setLayout(panelUserMLayout);
        panelUserMLayout.setHorizontalGroup(
            panelUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserMLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelModify)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelUserMLayout.setVerticalGroup(
            panelUserMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserMLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelModify)
                .addContainerGap())
        );

        panelUserL.setBackground(java.awt.Color.black);

        labelMostrar.setBackground(java.awt.Color.white);
        labelMostrar.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelMostrar.setForeground(java.awt.Color.white);
        labelMostrar.setText("MOSTRAR");
        labelMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMostrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUserLLayout = new javax.swing.GroupLayout(panelUserL);
        panelUserL.setLayout(panelUserLLayout);
        panelUserLLayout.setHorizontalGroup(
            panelUserLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMostrar)
                .addGap(21, 21, 21))
        );
        panelUserLLayout.setVerticalGroup(
            panelUserLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelMostrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelUserOptionsLayout = new javax.swing.GroupLayout(panelUserOptions);
        panelUserOptions.setLayout(panelUserOptionsLayout);
        panelUserOptionsLayout.setHorizontalGroup(
            panelUserOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUserD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUserM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUserR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUserL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUserOptionsLayout.setVerticalGroup(
            panelUserOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUserD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUserL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1.add(panelUserOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, 210));

        panelDeptOptions.setBackground(java.awt.Color.black);
        panelDeptOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelDeptOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDeptOptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDeptOptionsMouseExited(evt);
            }
        });

        panelDeptD.setBackground(java.awt.Color.black);

        labelDeleteDept.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelDeleteDept.setForeground(java.awt.Color.white);
        labelDeleteDept.setText("ELIMINAR DEPT");
        labelDeleteDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDeleteDeptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDeleteDeptMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDeptDLayout = new javax.swing.GroupLayout(panelDeptD);
        panelDeptD.setLayout(panelDeptDLayout);
        panelDeptDLayout.setHorizontalGroup(
            panelDeptDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDeleteDept)
                .addGap(32, 32, 32))
        );
        panelDeptDLayout.setVerticalGroup(
            panelDeptDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeptDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDeleteDept)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelDeptA.setBackground(java.awt.Color.black);

        labelAgregarDept.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelAgregarDept.setForeground(java.awt.Color.white);
        labelAgregarDept.setText("AGREGAR DEPT.");
        labelAgregarDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAgregarDeptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAgregarDeptMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDeptALayout = new javax.swing.GroupLayout(panelDeptA);
        panelDeptA.setLayout(panelDeptALayout);
        panelDeptALayout.setHorizontalGroup(
            panelDeptALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAgregarDept)
                .addGap(32, 32, 32))
        );
        panelDeptALayout.setVerticalGroup(
            panelDeptALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAgregarDept)
                .addGap(15, 15, 15))
        );

        panelDeptM.setBackground(java.awt.Color.black);

        labelModifyDept.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelModifyDept.setForeground(java.awt.Color.white);
        labelModifyDept.setText("MODIFICAR DEPT.");
        labelModifyDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModifyDeptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModifyDeptMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDeptMLayout = new javax.swing.GroupLayout(panelDeptM);
        panelDeptM.setLayout(panelDeptMLayout);
        panelDeptMLayout.setHorizontalGroup(
            panelDeptMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptMLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelModifyDept)
                .addGap(25, 25, 25))
        );
        panelDeptMLayout.setVerticalGroup(
            panelDeptMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptMLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelModifyDept)
                .addContainerGap())
        );

        panelDeptL.setBackground(java.awt.Color.black);

        labelMostrarDepts.setBackground(java.awt.Color.white);
        labelMostrarDepts.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        labelMostrarDepts.setForeground(java.awt.Color.white);
        labelMostrarDepts.setText("MOSTRAR DEPTS");
        labelMostrarDepts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMostrarDeptsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMostrarDeptsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDeptLLayout = new javax.swing.GroupLayout(panelDeptL);
        panelDeptL.setLayout(panelDeptLLayout);
        panelDeptLLayout.setHorizontalGroup(
            panelDeptLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMostrarDepts)
                .addGap(29, 29, 29))
        );
        panelDeptLLayout.setVerticalGroup(
            panelDeptLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptLLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelMostrarDepts)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelDeptOptionsLayout = new javax.swing.GroupLayout(panelDeptOptions);
        panelDeptOptions.setLayout(panelDeptOptionsLayout);
        panelDeptOptionsLayout.setHorizontalGroup(
            panelDeptOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDeptM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDeptA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDeptL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDeptD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDeptOptionsLayout.setVerticalGroup(
            panelDeptOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeptOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(panelDeptA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeptM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeptD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeptL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(panelDeptOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 210));
        panelDeptOptions.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseEntered
        this.menuUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserOptions.setVisible(true);
    }//GEN-LAST:event_menuUserMouseEntered

    private void panelUserOptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUserOptionsMouseEntered
        this.panelUserOptions.setVisible(true);
    }//GEN-LAST:event_panelUserOptionsMouseEntered

    private void panelUserOptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUserOptionsMouseExited
        this.panelUserOptions.setVisible(false);
    }//GEN-LAST:event_panelUserOptionsMouseExited

    private void menuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseExited
       
    }//GEN-LAST:event_menuUserMouseExited

    private void labelRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarMouseEntered
        this.labelRegistrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserOptions.setVisible(true);
        this.labelRegistrar.setForeground(Color.black);
        this.labelRegistrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserR.setBackground(Color.white);
    }//GEN-LAST:event_labelRegistrarMouseEntered

    private void labelModifyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyMouseEntered
        this.labelModify.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserOptions.setVisible(true);
        this.labelModify.setForeground(Color.black);
        this.labelModify.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserM.setBackground(Color.white);
    }//GEN-LAST:event_labelModifyMouseEntered

    private void labelDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeleteMouseEntered
        this.labelDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserOptions.setVisible(true);
        this.labelDelete.setForeground(Color.black);
        this.labelDelete.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserD.setBackground(Color.white);
    }//GEN-LAST:event_labelDeleteMouseEntered

    private void labelMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarMouseEntered
        this.labelMostrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserOptions.setVisible(true);
        this.labelMostrar.setForeground(Color.black);
        this.labelMostrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelUserL.setBackground(Color.white);
    }//GEN-LAST:event_labelMostrarMouseEntered

    private void labelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarMouseExited
        this.labelRegistrar.setForeground(Color.white);
        this.panelUserR.setBackground(Color.black);
    }//GEN-LAST:event_labelRegistrarMouseExited

    private void labelModifyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyMouseExited
        this.labelModify.setForeground(Color.white);
        this.panelUserM.setBackground(Color.black);
    }//GEN-LAST:event_labelModifyMouseExited

    private void labelDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeleteMouseExited
        this.labelDelete.setForeground(Color.white);
        this.panelUserD.setBackground(Color.black);
    }//GEN-LAST:event_labelDeleteMouseExited

    private void labelMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarMouseExited
        this.labelMostrar.setForeground(Color.white);
        this.panelUserL.setBackground(Color.black);
    }//GEN-LAST:event_labelMostrarMouseExited

    private void departamentoMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentoMenuMouseEntered
        this.departamentoMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelDeptOptions.setVisible(true);
    }//GEN-LAST:event_departamentoMenuMouseEntered

    private void departamentoMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departamentoMenuMouseExited
        
    }//GEN-LAST:event_departamentoMenuMouseExited

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        this.exitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.exitButton.setBackground(Color.red);
        this.exitButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        this.exitButton.setBackground(Color.black);
        this.exitButton.setForeground(Color.white);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void labelDeleteDeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeleteDeptMouseEntered
        this.panelDeptOptions.setVisible(true);
        this.labelDeleteDept.setForeground(Color.black);
        this.labelDeleteDept.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelDeptD.setBackground(Color.white);
    }//GEN-LAST:event_labelDeleteDeptMouseEntered

    private void labelDeleteDeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeleteDeptMouseExited
        this.labelDeleteDept.setForeground(Color.white);
        this.panelDeptD.setBackground(Color.black);
    }//GEN-LAST:event_labelDeleteDeptMouseExited

    private void labelAgregarDeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAgregarDeptMouseEntered
        this.panelDeptOptions.setVisible(true);
        this.labelAgregarDept.setForeground(Color.black);
        this.labelAgregarDept.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelDeptA.setBackground(Color.white);
    }//GEN-LAST:event_labelAgregarDeptMouseEntered

    private void labelAgregarDeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAgregarDeptMouseExited
        this.labelAgregarDept.setForeground(Color.white);
        this.panelDeptA.setBackground(Color.black);
    }//GEN-LAST:event_labelAgregarDeptMouseExited

    private void labelModifyDeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyDeptMouseEntered
        this.panelDeptOptions.setVisible(true);
        this.labelModifyDept.setForeground(Color.black);
        this.labelModifyDept.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelDeptM.setBackground(Color.white);
    }//GEN-LAST:event_labelModifyDeptMouseEntered

    private void labelModifyDeptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyDeptMouseExited
        this.labelModifyDept.setForeground(Color.white);
        this.panelDeptM.setBackground(Color.black);
    }//GEN-LAST:event_labelModifyDeptMouseExited

    private void labelMostrarDeptsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarDeptsMouseEntered
        this.panelDeptOptions.setVisible(true);
        this.labelMostrarDepts.setForeground(Color.black);
        this.labelMostrarDepts.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.panelDeptL.setBackground(Color.white);
    }//GEN-LAST:event_labelMostrarDeptsMouseEntered

    private void labelMostrarDeptsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMostrarDeptsMouseExited
        this.labelMostrarDepts.setForeground(Color.white);
        this.panelDeptL.setBackground(Color.black);
    }//GEN-LAST:event_labelMostrarDeptsMouseExited

    private void panelDeptOptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeptOptionsMouseEntered
        this.panelDeptOptions.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_panelDeptOptionsMouseEntered

    private void panelDeptOptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDeptOptionsMouseExited
        this.panelDeptOptions.setVisible(false);
    }//GEN-LAST:event_panelDeptOptionsMouseExited

    private void panelContainerModulesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelContainerModulesMouseEntered
        this.panelUserOptions.setVisible(false);
        this.panelDeptOptions.setVisible(false);
    }//GEN-LAST:event_panelContainerModulesMouseEntered

    private void labelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistrarMouseClicked
        this.panelUserOptions.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_labelRegistrarMouseClicked

    private void labelModifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModifyMouseClicked
        this.panelUserOptions.setVisible(false);
        l2.setVisible(true);
    }//GEN-LAST:event_labelModifyMouseClicked

    private void labelDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDeleteMouseClicked
        this.panelUserOptions.setVisible(false);
        l3.setVisible(true);
    }//GEN-LAST:event_labelDeleteMouseClicked

    private void menuCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoryMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoryMouseEntered

    private void menuCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCategoryMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCategoryMouseExited

    private void menuProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProductosMouseEntered

    private void menuProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProductosMouseExited

    private void menuProductos1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductos1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProductos1MouseEntered

    private void menuProductos1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductos1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProductos1MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMD;
    private javax.swing.JLabel departamentoMenu;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAgregarDept;
    private javax.swing.JLabel labelDelete;
    private javax.swing.JLabel labelDeleteDept;
    private javax.swing.JLabel labelModify;
    private javax.swing.JLabel labelModifyDept;
    private javax.swing.JLabel labelMostrar;
    private javax.swing.JLabel labelMostrarDepts;
    private javax.swing.JLabel labelRegistrar;
    private javax.swing.JLabel menuCategory;
    private javax.swing.JLabel menuProductos;
    private javax.swing.JLabel menuProductos1;
    private javax.swing.JLabel menuUser;
    private javax.swing.JPanel panelContainerModules;
    private javax.swing.JPanel panelDeptA;
    private javax.swing.JPanel panelDeptD;
    private javax.swing.JPanel panelDeptL;
    private javax.swing.JPanel panelDeptM;
    private javax.swing.JPanel panelDeptOptions;
    private javax.swing.JPanel panelUserD;
    private javax.swing.JPanel panelUserL;
    private javax.swing.JPanel panelUserM;
    private javax.swing.JPanel panelUserOptions;
    private javax.swing.JPanel panelUserR;
    // End of variables declaration//GEN-END:variables
}
