/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.una.proyecto3_progra3.view;

import com.una.proyecto3_progra3.view.usuario.frmAgregarUsuario;
import com.una.proyecto3_progra3.view.usuario.frmMostrar;
import java.awt.Dimension;

/**
 *
 * @author Dylan M
 */
public class MDI extends javax.swing.JFrame {

    frmAgregarUsuario frmAgregarU;
    frmMostrar frmMostrarU;
    public MDI() {
        frmAgregarU = new frmAgregarUsuario();
        frmMostrarU = new frmMostrar();
        initComponents();
        this.desktopPane.add(frmAgregarU);
        this.desktopPane.add(frmMostrarU);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuAgregar = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        addMenuItem = new javax.swing.JMenuItem();
        updateMenuItem = new javax.swing.JMenuItem();
        deletMenuItem = new javax.swing.JMenuItem();
        mostrarMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userMenu.setMnemonic('f');
        userMenu.setText("Administracion de Usuarios");

        addMenuItem.setMnemonic('o');
        addMenuItem.setText("Agregar");
        addMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(addMenuItem);

        updateMenuItem.setMnemonic('s');
        updateMenuItem.setText("Modificar");
        userMenu.add(updateMenuItem);

        deletMenuItem.setMnemonic('a');
        deletMenuItem.setText("Eliminar");
        userMenu.add(deletMenuItem);

        mostrarMenuItem.setText("Mostrar");
        mostrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(mostrarMenuItem);

        menuAgregar.add(userMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuAgregar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuAgregar.add(helpMenu);

        setJMenuBar(menuAgregar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuItemActionPerformed
        frmAgregarU.setVisible(true);
    }//GEN-LAST:event_addMenuItemActionPerformed

    private void mostrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMenuItemActionPerformed
        frmMostrarU.setVisible(true);
        frmMostrarU.listar();
    }//GEN-LAST:event_mostrarMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem addMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deletMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuAgregar;
    private javax.swing.JMenuItem mostrarMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem updateMenuItem;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables

}
